# Generated by Django 5.0.4 on 2024-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("owner", models.CharField(max_length=100)),
                ("rating", models.FloatField(default=5.0)),
                ("validated", models.BooleanField(default=False)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("info", models.TextField()),
                (
                    "is_verified",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=10
                    ),
                ),
                ("date_joined", models.DateField(auto_now=True)),
                ("country", models.CharField(max_length=50)),
            ],
        ),
    ]
