# Generated by Django 5.0.4 on 2024-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_rename_article_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=300)),
                ("subject", models.CharField(max_length=350)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
